debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[accessLog]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
#domain = "yoloctf.org"
watch = true
exposedByDefault = false

[acme]
email = "admin@yoloctf.org"
storage = "acme.json"
entryPoint = "https"
#onHostRule = true
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
acmeLogging = true

[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
main = "yoloctf.org"


#
# Some rules for stat server on Host
# IP => Traefik LAN Gw
[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://172.19.0.1:7000"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "PathPrefix:/stats/;ReplacePathRegex: ^/stats/(.*) /$1"

